defaults:
  - _self_

frame_stack: 4
img_size: 84
num_channels: 32
latent_dim: 64
action_dim: 2
mlp_dim: 256




﻿save_best: False
plot_agents: False
collect_stats: True
stats_directory: ../../../src/bbrl_algos/algos/algorithm_stats/

logger:
      classname: bbrl.utils.logger.TFLogger  #Our logger or the logger used in BBRL? 
      log_dir: ./droQ_logs/
      verbose: False
      every_n_seconds: 10


algorithm:

      seed:
            train: 335
            eval: 983
            q: 123
            explorer: 456
            torch: 789
            act: 234

      nb_seeds: 1
      n_envs: 1
      n_steps_train: 256
      n_steps: 2_000_000
      max_grad_norm: 0.5
      buffer_size: 1000000
      batch_size: 256
      eval_interval: 2000
      nb_evals: 10
      learning_starts: 5000
      tau_target: 0.005
      discount_factor: 0.99
      action_noise: 0.1
      optim_n_updates: 3
      architecture:
            
            

gym_env:
      env_name: # ?
